export { default as Header } from "./Header/Header";
export { default as About } from "./About/About";
export { default as Partners } from "./Partners/Partners";
export { default as Projects } from "./Projects/Projects";
export { default as Services } from "./Services/Services";
export { default as Advantages } from "./Advantages/Advantages";
export { default as Feedbacks } from "./Feedbacks/Feedbacks";
export { default as Contact } from "./Contact/Contact";
export { default as Footer } from "./Footer/Footer";
